Determine default assembly name based on csproj filename

diff --git a/2.0/s2i/bin/assemble b/2.0/s2i/bin/assemble
--- a/2.0/s2i/bin/assemble
+++ b/2.0/s2i/bin/assemble
@@ -31,12 +31,6 @@ if [ -n "${DOTNET_NPM_TOOLS}" ]; then
   popd
 fi
 
-# project.json defaults to naming the assembly the same as the folder
-if [ -n "$DOTNET_ASSEMBLY_NAME" ]; then
-  mkdir "$DOTNET_ASSEMBLY_NAME"
-  cd "$DOTNET_ASSEMBLY_NAME"
-fi
-
 echo "---> Copying application source ..."
 cp -Rf /tmp/src/. ./
 
@@ -44,7 +38,17 @@ cp -Rf /tmp/src/. ./
 if [ -n "$DOTNET_ASSEMBLY_NAME" ]; then
   APP_DLL_NAME="${DOTNET_ASSEMBLY_NAME}.dll"
 else
-  APP_DLL_NAME="$(basename "$(realpath "${DOTNET_STARTUP_PROJECT}")").dll"
+  CSPROJFILES=(`find "${DOTNET_STARTUP_PROJECT}" -maxdepth 1 -name "*.csproj"`)
+  if [ ${#CSPROJFILES[@]} -eq 1 ]; then
+    CSPROJFILE=$(basename ${CSPROJFILES[0]})
+    APP_DLL_NAME="${CSPROJFILE: : -7}.dll"
+  elif [ ${#CSPROJFILES[@]} -eq 0 ]; then
+    echo "error: DOTNET_STARTUP_PROJECT has no csproj file"
+    exit 1
+  else
+    echo "error: DOTNET_STARTUP_PROJECT contains multiple csproj files"
+    exit 1
+  fi
 fi
 
 # Build nuget sources list for when doing the restore
